# Generated by Django 6.0.6 on 2026-07-05 21:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0010_seed_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEnxoval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='item de enxoval')),
                ('unidade', models.CharField(default='peça', max_length=20, verbose_name='unidade')),
                ('minimo', models.PositiveIntegerField(default=0, verbose_name='estoque mínimo (limpo)')),
                ('por_faxina', models.PositiveSmallIntegerField(default=0, help_text='Quantas peças deste item uma faxina recolhe (em uso → suja).', verbose_name='peças por faxina')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'item de enxoval',
                'verbose_name_plural': 'enxoval',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ServicoLavanderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='serviço')),
                ('unidade', models.CharField(choices=[('peca', 'Peça'), ('kg', 'Quilo')], default='peca', max_length=4, verbose_name='unidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'serviço de lavanderia',
                'verbose_name_plural': 'tabela de preços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEnxoval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('limpa', 'Limpa (rouparia)'), ('em_uso', 'Em uso'), ('suja', 'Suja'), ('lavando', 'Lavando')], max_length=8, verbose_name='estado')),
                ('quantidade', models.IntegerField(verbose_name='quantidade (± no estado)')),
                ('motivo', models.CharField(max_length=40, verbose_name='motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_enxoval', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='lavanderia.itemenxoval', verbose_name='item')),
                ('uh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_enxoval', to='nucleo.uh', verbose_name='quarto')),
            ],
            options={
                'verbose_name': 'movimento de enxoval',
                'verbose_name_plural': 'movimentos de enxoval',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OrdemLavanderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(blank=True, help_text='Ex.: quarto 12, avulso balcão.', max_length=60, verbose_name='identificação')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='pronto para')),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('lavando', 'Lavando'), ('pronta', 'Pronta'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='recebida', max_length=10, verbose_name='status')),
                ('destino', models.CharField(blank=True, choices=[('caixa', 'Pagamento imediato'), ('conta', 'Conta do quarto')], max_length=8, verbose_name='destino')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto (R$)')),
                ('conta_ref', models.CharField(blank=True, max_length=120, verbose_name='conta do quarto')),
                ('recebida_em', models.DateTimeField(auto_now_add=True, verbose_name='recebida em')),
                ('entregue_em', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_lavanderia', to='nucleo.pessoa', verbose_name='cliente/hóspede')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_lavanderia', to=settings.AUTH_USER_MODEL, verbose_name='recebida por')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_lavanderia', to='nucleo.formapagamento', verbose_name='forma de pagamento')),
                ('movimento_caixa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_lavanderia', to='nucleo.movimentocaixa', verbose_name='recebimento no caixa')),
            ],
            options={
                'verbose_name': 'ordem de lavanderia',
                'verbose_name_plural': 'ordens de lavanderia',
                'ordering': ['-recebida_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemLavanderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário (R$)')),
                ('natureza', models.CharField(default='servico', max_length=10, verbose_name='natureza fiscal')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='lançado em')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='lavanderia.ordemlavanderia', verbose_name='ordem')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='lavanderia.servicolavanderia', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'item da ordem',
                'verbose_name_plural': 'itens da ordem',
                'ordering': ['criado_em'],
            },
        ),
    ]
