# Generated by Django 6.0.6 on 2026-07-05 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0010_seed_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Manhã, Tarde, Noite.', max_length=40, verbose_name='nome')),
                ('setor', models.CharField(choices=[('recepcao', 'Recepção'), ('governanca', 'Governança'), ('cozinha', 'Cozinha/Restaurante'), ('manutencao', 'Manutenção'), ('geral', 'Geral')], default='geral', max_length=12, verbose_name='setor')),
                ('inicio', models.TimeField(verbose_name='início')),
                ('fim', models.TimeField(verbose_name='fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['setor', 'inicio'],
            },
        ),
        migrations.CreateModel(
            name='Atribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes_escala', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='nucleo.funcionario', verbose_name='funcionário')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='escala.turno', verbose_name='turno')),
            ],
            options={
                'verbose_name': 'atribuição de turno',
                'verbose_name_plural': 'atribuições de turno',
                'ordering': ['data', 'turno__inicio'],
            },
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('folga', 'Folga'), ('ferias', 'Férias'), ('atestado', 'Atestado'), ('outro', 'Outro')], default='folga', max_length=10, verbose_name='tipo')),
                ('inicio', models.DateField(verbose_name='início')),
                ('fim', models.DateField(verbose_name='fim')),
                ('observacao', models.CharField(blank=True, max_length=120, verbose_name='observação')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ausencias_criadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='nucleo.funcionario', verbose_name='funcionário')),
            ],
            options={
                'verbose_name': 'ausência',
                'verbose_name_plural': 'ausências',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='TrocaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=160, verbose_name='motivo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=10, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='solicitada em')),
                ('decidido_em', models.DateTimeField(blank=True, null=True, verbose_name='decidida em')),
                ('atribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas', to='escala.atribuicao', verbose_name='atribuição')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_decididas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_solicitadas', to='nucleo.funcionario', verbose_name='solicitante')),
                ('substituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_recebidas', to='nucleo.funcionario', verbose_name='substituto')),
            ],
            options={
                'verbose_name': 'troca de turno',
                'verbose_name_plural': 'trocas de turno',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='atribuicao',
            constraint=models.UniqueConstraint(fields=('turno', 'funcionario', 'data'), name='escala_atribuicao_unica'),
        ),
    ]
