# Generated by Django 6.0.7 on 2026-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='data')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('municipal', models.BooleanField(default=False, help_text='Feriado municipal de Itá/SC (não nacional).', verbose_name='municipal')),
            ],
            options={
                'verbose_name': 'feriado',
                'verbose_name_plural': 'feriados',
                'ordering': ['data'],
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='min_pessoas',
            field=models.PositiveSmallIntegerField(default=1, help_text='Quantos funcionários o gerador deve alocar neste turno por dia.', verbose_name='cobertura mínima'),
        ),
    ]
