# Generated by Django 6.0.7 on 2026-08-25 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_feriado_turno_min_pessoas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaPublicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='segunda-feira da semana')),
                ('setor', models.CharField(blank=True, help_text='Vazio = todos.', max_length=12, verbose_name='setor')),
                ('publicado_em', models.DateTimeField(auto_now=True, verbose_name='publicada em')),
                ('forcado', models.BooleanField(default=False, verbose_name='publicada com violação')),
                ('justificativa', models.CharField(blank=True, max_length=240, verbose_name='justificativa')),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semanas_publicadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'semana publicada',
                'verbose_name_plural': 'semanas publicadas',
                'ordering': ['-inicio'],
                'constraints': [models.UniqueConstraint(fields=('inicio', 'setor'), name='escala_semana_unica')],
            },
        ),
    ]
