# Generated by Django 6.0.7 on 2026-08-27 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0003_semanapublicada'),
        ('nucleo', '0031_conceder_remuneracao_gerentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('inicio', models.TimeField(verbose_name='início')),
                ('fim', models.TimeField(verbose_name='fim')),
                ('tipo', models.CharField(choices=[('banco', 'Banco de horas'), ('extra', 'Hora extra')], default='banco', max_length=6, verbose_name='tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='lançada em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horas_extras_lancadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extras', to='nucleo.funcionario', verbose_name='funcionário')),
            ],
            options={
                'verbose_name': 'hora extra',
                'verbose_name_plural': 'horas extras',
                'ordering': ['data', 'inicio'],
            },
        ),
    ]
