# Generated by Django 6.0.7 on 2026-08-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0004_horaextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='atribuicao',
            name='compensacao_feriado',
            field=models.CharField(blank=True, choices=[('folga', 'Folga compensatória'), ('dobro', 'Pagamento em dobro')], max_length=6, verbose_name='feriado — compensação'),
        ),
    ]
