# Generated by Django 6.0.6 on 2026-07-04 14:10

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0005_seed_formas_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Necessária para a ExclusionConstraint (igualdade de FK + overlap de range)
        BtreeGistExtension(),
        migrations.CreateModel(
            name='ContaHospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=10, verbose_name='status')),
                ('aberta_em', models.DateTimeField(auto_now_add=True, verbose_name='aberta em')),
                ('fechada_em', models.DateTimeField(blank=True, null=True, verbose_name='fechada em')),
            ],
            options={
                'verbose_name': 'conta da hospedagem',
                'verbose_name_plural': 'contas de hospedagem',
            },
        ),
        migrations.CreateModel(
            name='PagamentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='reservas.contahospedagem', verbose_name='conta')),
                ('movimento_caixa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento_conta', to='nucleo.movimentocaixa', verbose_name='movimento de caixa')),
            ],
            options={
                'verbose_name': 'pagamento da conta',
                'verbose_name_plural': 'pagamentos da conta',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='check-in')),
                ('checkout', models.DateField(verbose_name='check-out')),
                ('adultos', models.PositiveSmallIntegerField(default=2, verbose_name='adultos')),
                ('criancas', models.PositiveSmallIntegerField(default=0, verbose_name='crianças')),
                ('status', models.CharField(choices=[('orcamento', 'Orçamento'), ('pre_reserva', 'Pré-reserva'), ('confirmada', 'Confirmada'), ('hospedada', 'Hospedada'), ('checkout', 'Check-out'), ('cancelada', 'Cancelada'), ('no_show', 'No-show')], default='pre_reserva', max_length=12, verbose_name='status')),
                ('canal', models.CharField(choices=[('balcao', 'Balcão/telefone'), ('whatsapp', 'WhatsApp'), ('site', 'Site/APP'), ('ota', 'Booking/Airbnb (OTA)')], default='balcao', max_length=10, verbose_name='canal')),
                ('valor_diaria', models.DecimalField(decimal_places=2, help_text='Preenchida pela tarifa vigente; alteração manual exige gerência.', max_digits=10, verbose_name='diária acordada (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('checkin_real', models.DateTimeField(blank=True, null=True, verbose_name='check-in realizado em')),
                ('checkout_real', models.DateTimeField(blank=True, null=True, verbose_name='check-out realizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='nucleo.pessoa', verbose_name='hóspede')),
                ('uh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='nucleo.uh', verbose_name='UH')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-checkin'],
            },
        ),
        migrations.AddField(
            model_name='contahospedagem',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conta', to='reservas.reserva', verbose_name='reserva'),
        ),
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('movimento_caixa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adiantamento', to='nucleo.movimentocaixa', verbose_name='movimento de caixa')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adiantamentos', to='reservas.reserva', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'adiantamento',
                'verbose_name_plural': 'adiantamentos',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Acompanhante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('documento', models.CharField(blank=True, max_length=30, verbose_name='documento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhantes', to='reservas.reserva', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'acompanhante',
                'verbose_name_plural': 'acompanhantes',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('super_alta', 'Super alta'), ('feriado', 'Feriado')], max_length=12, verbose_name='classificação da temporada')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='diária (R$)')),
                ('tipo_uh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='nucleo.tipouh', verbose_name='tipo de UH')),
            ],
            options={
                'verbose_name': 'tarifa',
                'verbose_name_plural': 'tarifas',
                'ordering': ['tipo_uh__nome', 'classificacao'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diaria', 'Diária'), ('consumo', 'Consumo'), ('servico', 'Serviço'), ('desconto', 'Desconto')], max_length=10, verbose_name='tipo')),
                ('natureza', models.CharField(choices=[('servico', 'Serviço'), ('consumo', 'Consumo')], max_length=10, verbose_name='natureza fiscal')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='lançado em')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='reservas.contahospedagem', verbose_name='conta')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_conta', to=settings.AUTH_USER_MODEL, verbose_name='lançado por')),
            ],
            options={
                'verbose_name': 'lançamento da conta',
                'verbose_name_plural': 'lançamentos da conta',
                'ordering': ['criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='lancamento_conta_valor_positivo')],
            },
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('checkout__gt', models.F('checkin'))), name='reserva_checkout_depois_do_checkin'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['pre_reserva', 'confirmada', 'hospedada'])), expressions=[(models.F('uh'), '='), (models.Func(models.F('checkin'), models.F('checkout'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='reserva_sem_overbooking'),
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.UniqueConstraint(fields=('tipo_uh', 'classificacao'), name='tarifa_unica_por_tipo_e_classificacao'),
        ),
    ]
