# Generated by Django 6.0.6 on 2026-07-04 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_pessoa_tipo_agencia'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='faturamento',
            field=models.CharField(choices=[('particular', 'Particular (o hóspede paga)'), ('agencia', 'Agência'), ('empresa', 'Empresa')], default='particular', max_length=12, verbose_name='faturamento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='titular',
            field=models.ForeignKey(blank=True, help_text='Quem paga a conta, quando não é o próprio hóspede (agência/empresa).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_faturadas', to='nucleo.pessoa', verbose_name='titular do faturamento'),
        ),
    ]
