# Generated by Django 6.0.6 on 2026-07-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_alter_entradalogbook_options_alter_tipouh_options_and_more'),
        ('reservas', '0002_reserva_faturamento_reserva_titular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contahospedagem',
            options={'verbose_name': 'conta do quarto', 'verbose_name_plural': 'contas de quarto'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='canal',
            field=models.CharField(choices=[('balcao', 'Balcão/telefone'), ('whatsapp', 'WhatsApp'), ('site', 'Site/APP'), ('ota', 'Sites de reserva (Booking/Airbnb)')], default='balcao', max_length=10, verbose_name='canal'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='checkin',
            field=models.DateField(verbose_name='entrada (check-in)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='checkin_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='entrada realizada em'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='checkout',
            field=models.DateField(verbose_name='saída (check-out)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='checkout_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='saída realizada em'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('pre_reserva', 'Pré-reserva'), ('confirmada', 'Confirmada'), ('hospedada', 'Hospedada'), ('checkout', 'Saída'), ('cancelada', 'Cancelada'), ('no_show', 'Não compareceu')], default='pre_reserva', max_length=12, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='uh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='nucleo.uh', verbose_name='quarto'),
        ),
    ]
