# Generated by Django 6.0.6 on 2026-07-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_contahospedagem_options_alter_reserva_canal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='expira_em',
            field=models.DateTimeField(blank=True, help_text='Pré-reserva de canal (site) segura o quarto só até aqui; depois expira.', null=True, verbose_name='retenção até'),
        ),
    ]
