# Generated by Django 6.0.6 on 2026-07-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_expira_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoconta',
            name='observacao',
            field=models.CharField(blank=True, help_text="Quem pagou esta parte (ex.: 'Casal A', 'cartão do João') — para rateio.", max_length=120, verbose_name='pagador / observação'),
        ),
    ]
