# Generated by Django 6.0.7 on 2026-08-10 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0018_uh_tarifa_override'),
        ('reservas', '0005_pagamentoconta_observacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contahospedagem',
            options={'verbose_name': 'conta de hospedagem', 'verbose_name_plural': 'contas de hospedagem'},
        ),
        migrations.AlterField(
            model_name='contahospedagem',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta', to='reservas.reserva', verbose_name='reserva'),
        ),
        migrations.CreateModel(
            name='GrupoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(help_text='Ex.: «Grupo Ribeiro», «Casamento Ana & João».', max_length=120, verbose_name='identificação do grupo')),
                ('faturamento', models.CharField(choices=[('particular', 'Particular (o hóspede paga)'), ('agencia', 'Agência'), ('empresa', 'Empresa')], default='particular', max_length=12, verbose_name='faturamento')),
                ('canal', models.CharField(choices=[('balcao', 'Balcão/telefone'), ('whatsapp', 'WhatsApp'), ('site', 'Site/APP'), ('ota', 'Sites de reserva (Booking/Airbnb)')], default='balcao', max_length=10, verbose_name='canal')),
                ('checkin', models.DateField(verbose_name='entrada (check-in)')),
                ('checkout', models.DateField(verbose_name='saída (check-out)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('expira_em', models.DateTimeField(blank=True, help_text='Pré-reserva do grupo: segura os quartos só até aqui; depois expira.', null=True, verbose_name='retenção até')),
                ('encerrado_em', models.DateTimeField(blank=True, null=True, verbose_name='encerrado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_titular', to='nucleo.pessoa', verbose_name='titular (paga o folio)')),
            ],
            options={
                'verbose_name': 'reserva de grupo',
                'verbose_name_plural': 'reservas de grupo',
                'ordering': ['-checkin'],
            },
        ),
        migrations.AddField(
            model_name='contahospedagem',
            name='grupo',
            field=models.OneToOneField(blank=True, help_text='Folio do grupo: as diárias de todos os quartos do bloco.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folio', to='reservas.gruporeserva', verbose_name='grupo (folio-mãe)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Bloco de quartos: as diárias vão ao folio do grupo; o consumo fica na conta do quarto. Vazio = reserva avulsa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhas', to='reservas.gruporeserva', verbose_name='grupo (reserva-mãe)'),
        ),
        migrations.AddConstraint(
            model_name='contahospedagem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grupo__isnull', True), ('reserva__isnull', False)), models.Q(('grupo__isnull', False), ('reserva__isnull', True)), _connector='OR'), name='conta_reserva_xor_grupo'),
        ),
    ]
