# Generated by Django 6.0.7 on 2026-08-18 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0018_uh_tarifa_override'),
        ('reservas', '0006_alter_contahospedagem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaFNRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.BooleanField(default=False, verbose_name='hóspede responsável')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro / não informar')], max_length=1, verbose_name='sexo')),
                ('nacionalidade', models.CharField(blank=True, default='Brasileira', max_length=60, verbose_name='nacionalidade')),
                ('profissao', models.CharField(blank=True, max_length=80, verbose_name='profissão')),
                ('documento_tipo', models.CharField(choices=[('cpf', 'CPF'), ('rg', 'RG'), ('cnh', 'CNH'), ('passaporte', 'Passaporte'), ('certidao', 'Certidão de nascimento'), ('outro', 'Outro')], default='cpf', max_length=12, verbose_name='tipo de documento')),
                ('documento_numero', models.CharField(blank=True, max_length=30, verbose_name='nº do documento')),
                ('documento_emissor', models.CharField(blank=True, max_length=40, verbose_name='órgão emissor / país')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=40, verbose_name='país')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('motivo_viagem', models.CharField(blank=True, choices=[('lazer', 'Turismo / lazer'), ('negocios', 'Negócios / trabalho'), ('evento', 'Congresso / evento / feira'), ('saude', 'Saúde'), ('estudo', 'Estudo'), ('religiao', 'Religião'), ('compras', 'Compras'), ('outro', 'Outros')], max_length=12, verbose_name='motivo da viagem')),
                ('meio_transporte', models.CharField(blank=True, choices=[('carro', 'Automóvel'), ('onibus', 'Ônibus'), ('aviao', 'Avião'), ('moto', 'Motocicleta'), ('outro', 'Outro')], max_length=8, verbose_name='meio de transporte')),
                ('procedencia', models.CharField(blank=True, help_text='Cidade/UF/país de onde o hóspede veio nesta viagem.', max_length=120, verbose_name='procedência')),
                ('proximo_destino', models.CharField(blank=True, max_length=120, verbose_name='próximo destino')),
                ('origem', models.CharField(choices=[('recepcao', 'Recepção'), ('portal', 'Portal do hóspede')], default='recepcao', max_length=8, verbose_name='preenchida via')),
                ('preenchida_em', models.DateTimeField(blank=True, null=True, verbose_name='preenchida em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_fnrh', to='nucleo.pessoa', verbose_name='pessoa (cadastro)')),
                ('preenchida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_fnrh_preenchidas', to=settings.AUTH_USER_MODEL, verbose_name='preenchida por')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_fnrh', to='reservas.reserva', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'ficha FNRH',
                'verbose_name_plural': 'fichas FNRH',
                'ordering': ['-titular', 'nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('titular', True)), fields=('reserva',), name='fnrh_um_titular_por_reserva')],
            },
        ),
    ]
