# Generated by Django 6.0.7 on 2026-08-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_acompanhante_para_fnrh'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichafnrh',
            name='fnrh_hospede_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID do hóspede na FNRH'),
        ),
        migrations.AddField(
            model_name='fichafnrh',
            name='fnrh_pessoa_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID da pessoa na FNRH'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fnrh_erro',
            field=models.TextField(blank=True, verbose_name='último erro FNRH'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fnrh_reserva_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID da reserva na FNRH'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fnrh_sincronizada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sincronizada com a FNRH em'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fnrh_status',
            field=models.CharField(choices=[('nao_enviada', 'Não enviada'), ('pendente', 'Pendente de envio'), ('enviada', 'Enviada à FNRH'), ('erro', 'Erro no envio')], default='nao_enviada', max_length=12, verbose_name='situação FNRH'),
        ),
    ]
