# Generated by Django 6.0.7 on 2026-08-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_fichafnrh_fnrh_hospede_id_fichafnrh_fnrh_pessoa_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichafnrh',
            name='documento_tipo',
            field=models.CharField(choices=[('CPF', 'CPF'), ('PASSAPORTE', 'Passaporte')], default='CPF', max_length=12, verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='meio_transporte',
            field=models.CharField(blank=True, choices=[('AUTOMOVEL', 'Automóvel'), ('ONIBUS', 'Ônibus'), ('AVIAO', 'Avião'), ('MOTO', 'Motocicleta'), ('NAVIO_BARCO', 'Navio / barco'), ('TREM', 'Trem'), ('BICICLETA', 'Bicicleta'), ('PE', 'A pé')], max_length=15, verbose_name='meio de transporte'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='motivo_viagem',
            field=models.CharField(blank=True, choices=[('LAZER_FERIAS', 'Turismo / lazer / férias'), ('NEGOCIOS', 'Negócios / trabalho'), ('CONGRESSO_FEIRA', 'Congresso / feira / evento'), ('PARENTES_AMIGOS', 'Visita a parentes / amigos'), ('SAUDE', 'Saúde'), ('ESTUDOS_CURSOS', 'Estudos / cursos'), ('RELIGIAO', 'Religião'), ('COMPRAS', 'Compras')], max_length=20, verbose_name='motivo da viagem'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='sexo',
            field=models.CharField(blank=True, choices=[('HOMEM', 'Masculino'), ('MULHER', 'Feminino'), ('OUTRO', 'Outro'), ('NAOINFORMADO', 'Prefiro não informar')], max_length=12, verbose_name='sexo'),
        ),
    ]
