# Generated by Django 6.0.7 on 2026-08-23 18:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0025_uh_aceita_pet_uh_ar_condicionado_uh_diferenciais_and_more'),
        ('reservas', '0011_fnrh_valores_oficiais'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('super_alta', 'Super alta'), ('feriado', 'Feriado')], max_length=12, verbose_name='classificação da temporada')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='diária (R$)')),
                ('uh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas_unidade', to='nucleo.uh', verbose_name='quarto')),
            ],
            options={
                'verbose_name': 'tarifa por quarto',
                'verbose_name_plural': 'tarifas por quarto',
                'ordering': ['uh__numero', 'classificacao'],
                'constraints': [models.UniqueConstraint(fields=('uh', 'classificacao'), name='tarifa_unica_por_quarto_e_classificacao')],
            },
        ),
    ]
