# Generated by Django 6.0.6 on 2026-07-05 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0010_seed_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('arrumacao', 'Arrumação diária'), ('checkout', 'Check-out')], default='arrumacao', max_length=10, verbose_name='momento')),
                ('status', models.CharField(choices=[('conferida', 'Conferida'), ('reposta', 'Reposta'), ('cancelada', 'Cancelada')], default='conferida', max_length=10, verbose_name='status')),
                ('conta_ref', models.CharField(blank=True, max_length=120, verbose_name='conta do quarto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='conferida em')),
                ('reposto_em', models.DateTimeField(blank=True, null=True, verbose_name='reposta em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias_frigobar', to=settings.AUTH_USER_MODEL, verbose_name='conferido por')),
                ('reposto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposicoes_frigobar', to=settings.AUTH_USER_MODEL, verbose_name='reposta por')),
                ('uh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias_frigobar', to='nucleo.uh', verbose_name='quarto')),
            ],
            options={
                'verbose_name': 'conferência de frigobar',
                'verbose_name_plural': 'conferências de frigobar',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('quantidade', models.PositiveIntegerField(verbose_name='consumido')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário (R$)')),
                ('natureza', models.CharField(default='consumo', max_length=10, verbose_name='natureza fiscal')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='frigobar.conferencia', verbose_name='conferência')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_frigobar', to='nucleo.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item consumido',
                'verbose_name_plural': 'itens consumidos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='ItemComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='quantidade padrão')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicoes_frigobar', to='nucleo.produto', verbose_name='produto')),
                ('tipo_uh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao_frigobar', to='nucleo.tipouh', verbose_name='tipo de quarto')),
            ],
            options={
                'verbose_name': 'item de composição',
                'verbose_name_plural': 'composição do frigobar',
                'ordering': ['tipo_uh__nome', 'produto__nome'],
                'constraints': [models.UniqueConstraint(fields=('tipo_uh', 'produto'), name='frigobar_composicao_unica')],
            },
        ),
    ]
