# Generated by Django 6.0.7 on 2026-07-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frigobar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='conta_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='conta id'),
        ),
    ]
