# Generated by Django 6.0.6 on 2026-07-05 16:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0010_seed_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(choices=[('caixa', 'Pagamento imediato'), ('conta', 'Conta do quarto')], max_length=8, verbose_name='destino')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto (R$)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total (R$)')),
                ('conta_ref', models.CharField(blank=True, help_text='Quarto/hóspede onde o consumo foi lançado.', max_length=120, verbose_name='conta do quarto')),
                ('status', models.CharField(choices=[('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='fechada', max_length=10, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='data/hora')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_loja', to='nucleo.pessoa', verbose_name='cliente')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_loja', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_loja', to='nucleo.formapagamento', verbose_name='forma de pagamento')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_loja', to='nucleo.localestoque', verbose_name='local de estoque')),
                ('movimento_caixa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venda_loja', to='nucleo.movimentocaixa', verbose_name='recebimento no caixa')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('natureza', models.CharField(max_length=10, verbose_name='natureza fiscal')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário (R$)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal (R$)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda_loja', to='nucleo.produto', verbose_name='produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja.venda', verbose_name='venda')),
            ],
            options={
                'verbose_name': 'item da venda',
                'verbose_name_plural': 'itens da venda',
            },
        ),
    ]
