# Generated by Django 6.0.6 on 2026-07-05 19:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0010_seed_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True, verbose_name='nome/número')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(blank=True, help_text='Ex.: guarda-sol 4, espreguiçadeira 2.', max_length=60, verbose_name='identificação')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=10, verbose_name='status')),
                ('destino', models.CharField(blank=True, choices=[('caixa', 'Pagamento imediato'), ('conta', 'Conta do quarto')], max_length=8, verbose_name='destino')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto (R$)')),
                ('conta_ref', models.CharField(blank=True, max_length=120, verbose_name='conta do quarto')),
                ('aberta_em', models.DateTimeField(auto_now_add=True, verbose_name='aberta em')),
                ('fechada_em', models.DateTimeField(blank=True, null=True, verbose_name='fechada em')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='nucleo.pessoa', verbose_name='cliente/hóspede')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to=settings.AUTH_USER_MODEL, verbose_name='aberta por')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='nucleo.formapagamento', verbose_name='forma de pagamento')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='nucleo.localestoque', verbose_name='estoque de origem')),
                ('movimento_caixa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comanda', to='nucleo.movimentocaixa', verbose_name='recebimento no caixa')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='restaurante.mesa', verbose_name='mesa')),
            ],
            options={
                'verbose_name': 'comanda',
                'verbose_name_plural': 'comandas',
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('natureza', models.CharField(max_length=10, verbose_name='natureza fiscal')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='lançado em')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='restaurante.comanda', verbose_name='comanda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_comanda', to='nucleo.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item da comanda',
                'verbose_name_plural': 'itens da comanda',
                'ordering': ['criado_em'],
            },
        ),
    ]
