# Generated by Django 6.0.6 on 2026-07-05 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['nome'], 'verbose_name': 'ponto de atendimento', 'verbose_name_plural': 'pontos de atendimento'},
        ),
        migrations.AlterField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='restaurante.mesa', verbose_name='ponto'),
        ),
    ]
