# Generated by Django 6.0.7 on 2026-09-19 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0034_pessoa_aceita_whatsapp_pessoa_whatsapp_optin_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(default='Banco Safra', max_length=60, verbose_name='banco')),
                ('conta', models.CharField(blank=True, max_length=40, verbose_name='conta')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='período de')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='período até')),
                ('arquivo_nome', models.CharField(blank=True, max_length=200, verbose_name='arquivo')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='importado em')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extratos_importados', to=settings.AUTH_USER_MODEL, verbose_name='importado por')),
            ],
            options={
                'verbose_name': 'extrato bancário',
                'verbose_name_plural': 'extratos bancários',
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='LoteCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adquirente', models.CharField(default='SafraPay', max_length=40, verbose_name='adquirente')),
                ('arquivo_nome', models.CharField(blank=True, max_length=200, verbose_name='arquivo')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='importado em')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_cartao', to=settings.AUTH_USER_MODEL, verbose_name='importado por')),
            ],
            options={
                'verbose_name': 'lote de cartão',
                'verbose_name_plural': 'lotes de cartão',
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(verbose_name='data da venda')),
                ('data_liquidacao', models.DateField(blank=True, null=True, verbose_name='data da liquidação')),
                ('nsu', models.CharField(max_length=40, verbose_name='NSU')),
                ('autorizacao', models.CharField(blank=True, max_length=40, verbose_name='autorização')),
                ('bandeira', models.CharField(blank=True, max_length=30, verbose_name='bandeira')),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor bruto (R$)')),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='taxa (R$)')),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor líquido (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('conciliado', 'Conciliado'), ('sem_venda', 'Sem venda no caixa')], default='pendente', max_length=12, verbose_name='status')),
                ('divergencia_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='divergência de valor (R$)')),
                ('conciliado_em', models.DateTimeField(blank=True, null=True, verbose_name='conciliado em')),
                ('conciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_cartao_conciliadas', to=settings.AUTH_USER_MODEL, verbose_name='conciliado por')),
                ('lancamento_taxa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxa_cartao', to='nucleo.lancamentofinanceiro', verbose_name='lançamento da taxa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='conciliacao.lotecartao', verbose_name='lote')),
                ('movimento_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_cartao', to='nucleo.movimentocaixa', verbose_name='recebimento no caixa')),
            ],
            options={
                'verbose_name': 'transação de cartão',
                'verbose_name_plural': 'transações de cartão',
                'ordering': ['data_venda', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Positivo = crédito (entrada); negativo = débito (saída).', max_digits=12, verbose_name='valor (R$)')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('fitid', models.CharField(blank=True, max_length=100, verbose_name='id da transação (FITID)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('conciliado', 'Conciliado'), ('ignorado', 'Ignorado')], default='pendente', max_length=12, verbose_name='status')),
                ('confianca', models.CharField(blank=True, max_length=10, verbose_name='confiança')),
                ('conciliado_em', models.DateTimeField(blank=True, null=True, verbose_name='conciliado em')),
                ('conciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_extrato_conciliados', to=settings.AUTH_USER_MODEL, verbose_name='conciliado por')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_extrato', to='nucleo.contapagarreceber', verbose_name='conta a pagar/receber')),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='conciliacao.extratobancario', verbose_name='extrato')),
                ('movimento_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_extrato', to='nucleo.movimentocaixa', verbose_name='movimento de caixa')),
            ],
            options={
                'verbose_name': 'lançamento do extrato',
                'verbose_name_plural': 'lançamentos do extrato',
                'ordering': ['data', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fitid', ''), _negated=True), fields=('extrato', 'fitid'), name='lancext_fitid_unico_por_extrato')],
            },
        ),
    ]
