# Generated by Django 6.0.5 on 2026-05-27 19:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Categoria de Quarto',
                'verbose_name_plural': 'Categorias de Quartos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_boas_vindas', models.CharField(default='Bem-vindo(a), viajante ao', max_length=100, verbose_name='Texto de boas-vindas')),
                ('frase_hero', models.CharField(default='As engrenagens do tempo desaceleraram para você apreciar a beleza da natureza', max_length=200, verbose_name='Frase do hero')),
                ('telefone', models.CharField(default='+49 9 9999-9999', max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(default='5549999999999', max_length=20, verbose_name='WhatsApp (com DDI)')),
                ('email', models.EmailField(default='contato@pousadavotesta.com.br', max_length=254, verbose_name='Email')),
                ('endereco', models.CharField(default='Rodovia SC 117, KM 130 — Lago Azul, 89760-000 Ita - SC', max_length=200, verbose_name='Endereço')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('numero_viajantes', models.CharField(default='+5 mil', max_length=20, verbose_name='Número de viajantes')),
                ('numero_quartos', models.CharField(default='+30', max_length=20, verbose_name='Número de quartos')),
                ('numero_zonas', models.CharField(default='05', max_length=20, verbose_name='Número de zonas')),
                ('numero_avaliacoes', models.CharField(default='19 mil', max_length=20, verbose_name='Número de avaliações')),
                ('desconto_pix', models.PositiveSmallIntegerField(default=5, verbose_name='Desconto Pix (%)')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hospede', models.CharField(max_length=100, verbose_name='Nome do hóspede')),
                ('texto', models.TextField(verbose_name='Depoimento')),
                ('nota', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('plataforma', models.CharField(choices=[('booking', 'Booking.com'), ('google', 'Google'), ('tripadvisor', 'TripAdvisor'), ('instagram', 'Instagram'), ('site', 'Site'), ('outro', 'Outro')], max_length=20, verbose_name='Plataforma de origem')),
                ('data_avaliacao', models.DateField(verbose_name='Data da avaliação')),
                ('destaque', models.BooleanField(default=True, verbose_name='Exibir na home')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['ordem', '-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, help_text='Path SVG do ícone (Heroicons)', max_length=500, verbose_name='Ícone SVG')),
                ('destaque', models.BooleanField(default=True, verbose_name='Exibir na home')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=150, verbose_name='Legenda')),
                ('categoria', models.CharField(choices=[('pousada', 'Pousada'), ('quartos', 'Quartos'), ('natureza', 'Natureza'), ('gastronomia', 'Gastronomia'), ('experiencias', 'Experiências'), ('eventos', 'Eventos')], max_length=20, verbose_name='Categoria')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque (tamanho grande no grid)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionada em')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True, verbose_name='CPF')),
                ('observacoes', models.TextField(blank=True, help_text='Preferências, alergias, etc.', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Hóspede',
                'verbose_name_plural': 'Hóspedes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Réveillon 2026, Verão 2027', max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('alta', 'Alta Temporada'), ('baixa', 'Baixa Temporada'), ('feriado', 'Feriado / Evento')], max_length=10, verbose_name='Tipo')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
                ('multiplicador', models.DecimalField(decimal_places=2, default=1.0, help_text='1.00 = preço base, 1.30 = +30%, 0.80 = -20%', max_digits=4, verbose_name='Multiplicador de preço')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('descricao_curta', models.CharField(help_text='Texto exibido no card do site', max_length=200, verbose_name='Descrição curta')),
                ('capacidade', models.PositiveSmallIntegerField(verbose_name='Capacidade (hóspedes)')),
                ('metragem', models.PositiveSmallIntegerField(verbose_name='Metragem (m²)')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço base (noite)')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Status')),
                ('destaque', models.BooleanField(default=False, verbose_name='Exibir em destaque na home')),
                ('foto_principal', models.ImageField(blank=True, upload_to='quartos/', verbose_name='Foto principal')),
                ('nota_avaliacao', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota de avaliação')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quartos', to='core.categoriaquarto', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='quartos/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=150, verbose_name='Legenda')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.quarto', verbose_name='Quarto')),
            ],
            options={
                'verbose_name': 'Foto do Quarto',
                'verbose_name_plural': 'Fotos do Quarto',
                'ordering': ['ordem'],
            },
        ),
    ]
