# Generated by Django 6.0.5 on 2026-06-02 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=16, unique=True, verbose_name='Código da reserva')),
                ('data_checkin', models.DateField(verbose_name='Check-in')),
                ('data_checkout', models.DateField(verbose_name='Check-out')),
                ('num_hospedes', models.PositiveSmallIntegerField(default=1, verbose_name='Número de hóspedes')),
                ('preco_noite', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço por noite')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Ex: 5.00 para 5% de desconto (Pix)', max_digits=5, verbose_name='Desconto (%)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor total')),
                ('metodo_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pix', 'Pix'), ('cartao', 'Cartão de Crédito')], default='pendente', max_length=10, verbose_name='Método de pagamento')),
                ('pagamento_id', models.CharField(blank=True, max_length=100, verbose_name='ID do pagamento (Mercado Pago)')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Pagamento'), ('confirmada', 'Confirmada'), ('checkin', 'Check-in Realizado'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='aguardando', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.hospede', verbose_name='Hóspede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.quarto', verbose_name='Quarto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_checkout__gt', models.F('data_checkin'))), name='checkout_depois_checkin')],
            },
        ),
    ]
