# Generated by Django 6.0.5 on 2026-06-15 17:08

import apps.site.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='expira_em',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Expira em'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token público'),
        ),
        migrations.AlterField(
            model_name='fotogaleria',
            name='imagem',
            field=models.ImageField(upload_to='galeria/', validators=[apps.site.models.validar_tamanho_imagem], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='fotoquarto',
            name='imagem',
            field=models.ImageField(upload_to='quartos/', validators=[apps.site.models.validar_tamanho_imagem], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='foto_principal',
            field=models.ImageField(blank=True, upload_to='quartos/', validators=[apps.site.models.validar_tamanho_imagem], verbose_name='Foto principal'),
        ),
    ]
