# Generated by Django 6.0.6 on 2026-07-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reserva_expira_em_reserva_token_and_more'),
        ('nucleo', '0010_seed_almoxarifado'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='tipo_uh',
            field=models.ForeignKey(blank=True, help_text='Vincula este card ao tipo real do CRM (disponibilidade e preço).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vitrine_site', to='nucleo.tipouh', verbose_name='Tipo de quarto (CRM)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='crm_reserva_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reserva no CRM'),
        ),
    ]
