# Generated by Django 6.0.7 on 2026-07-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quarto_tipo_uh_reserva_crm_reserva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pix', 'Pix'), ('cartao', 'Cartão de Crédito'), ('boleto', 'Boleto')], default='pendente', max_length=10, verbose_name='Método de pagamento'),
        ),
    ]
