# Generated by Django 6.0.7 on 2026-08-23 19:02

import apps.site.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boleto_metodo_pagamento'),
        ('nucleo', '0025_uh_aceita_pet_uh_ar_condicionado_uh_diferenciais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitrineQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_curta', models.CharField(blank=True, help_text='Frase exibida no card. Vazio = usa a do tipo.', max_length=200, verbose_name='Descrição curta')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição completa')),
                ('foto_principal', models.ImageField(blank=True, upload_to='quartos/', validators=[apps.site.models.validar_tamanho_imagem], verbose_name='Foto principal')),
                ('tour_360_url', models.URLField(blank=True, help_text='Cole o link de embed do tour (Kuula, Matterport, Google Street View).', verbose_name='Tour 360° (URL de embed)')),
                ('metragem', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Metragem (m²)')),
                ('nota_avaliacao', models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota de avaliação')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque na home (os 9 melhores)')),
                ('publicar', models.BooleanField(default=True, verbose_name='Publicar no site')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('uh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitrine', to='nucleo.uh', verbose_name='Quarto (CRM)')),
            ],
            options={
                'verbose_name': 'Vitrine do quarto',
                'verbose_name_plural': 'Vitrine dos quartos',
                'ordering': ['ordem', 'uh__numero'],
            },
        ),
    ]
