# Generated by Django 6.0.6 on 2026-07-05 20:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0010_seed_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, help_text='Preencha quando não for um quarto (ex.: piscina, recepção).', max_length=80, verbose_name='área comum')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('corretiva', 'Corretiva'), ('preventiva', 'Preventiva')], default='corretiva', max_length=10, verbose_name='tipo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=8, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=12, verbose_name='status')),
                ('bloqueia_uh', models.BooleanField(default=False, help_text='O quarto sai da disponibilidade até a OS ser concluída.', verbose_name='bloquear o quarto durante o reparo')),
                ('custo_maodeobra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='mão de obra (R$)')),
                ('custo_pecas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='peças (R$)')),
                ('recorrencia_meses', models.PositiveSmallIntegerField(blank=True, help_text='Só para preventiva: repetir a cada N meses.', null=True, verbose_name='recorrência (meses)')),
                ('agendada_para', models.DateField(blank=True, null=True, verbose_name='agendada para')),
                ('aberta_em', models.DateTimeField(auto_now_add=True, verbose_name='aberta em')),
                ('iniciada_em', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('resolucao', models.TextField(blank=True, verbose_name='resolução')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico_abertas', to=settings.AUTH_USER_MODEL, verbose_name='aberta por')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('uh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='nucleo.uh', verbose_name='quarto')),
            ],
            options={
                'verbose_name': 'ordem de serviço',
                'verbose_name_plural': 'ordens de serviço',
                'ordering': ['-aberta_em'],
            },
        ),
    ]
