# Generated by Django 6.0.6 on 2026-07-05 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
        ('nucleo', '0010_seed_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='garantia_ate',
            field=models.DateField(blank=True, null=True, verbose_name='garantia até'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=60, verbose_name='nota fiscal / documento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='prestador',
            field=models.ForeignKey(blank=True, help_text='Empresa/fornecedor que executou o serviço terceirizado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='nucleo.pessoa', verbose_name='prestador (externo)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='previsto_para',
            field=models.DateField(blank=True, null=True, verbose_name='previsto para'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsável (interno)'),
        ),
    ]
