# Generated by Django 6.0.7 on 2026-07-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_ordemservico_garantia_ate_ordemservico_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='bloqueio_fim',
            field=models.DateField(blank=True, help_text='Vazio = bloqueado até a OS ser concluída.', null=True, verbose_name='bloqueio até'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='bloqueio_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='bloqueio de'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='bloqueia_uh',
            field=models.BooleanField(default=False, help_text='O quarto sai da disponibilidade no período do bloqueio.', verbose_name='bloquear o quarto durante o reparo'),
        ),
    ]
