# Generated by Django 6.0.6 on 2026-07-06 00:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_id', models.PositiveIntegerField(unique=True, verbose_name='reserva')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'acesso ao portal',
                'verbose_name_plural': 'acessos ao portal',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva_id', models.PositiveIntegerField(verbose_name='reserva')),
                ('uh_numero', models.CharField(blank=True, max_length=20, verbose_name='quarto')),
                ('tipo', models.CharField(choices=[('restaurante', 'Pedido no restaurante'), ('limpeza', 'Limpeza extra'), ('manutencao', 'Manutenção'), ('checkout', 'Check-out expresso')], max_length=12, verbose_name='tipo')),
                ('detalhe', models.CharField(blank=True, max_length=200, verbose_name='detalhe')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='em')),
            ],
            options={
                'verbose_name': 'solicitação do portal',
                'verbose_name_plural': 'solicitações do portal',
                'ordering': ['-criado_em'],
            },
        ),
    ]
