# Generated by Django 6.0.6 on 2026-07-06 17:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0010_seed_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFiscalProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(blank=True, max_length=10, verbose_name='NCM')),
                ('cfop', models.CharField(blank=True, max_length=5, verbose_name='CFOP')),
                ('cst_csosn', models.CharField(blank=True, max_length=5, verbose_name='CST/CSOSN')),
                ('origem', models.CharField(blank=True, default='0', max_length=1, verbose_name='origem')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_fiscal', to='nucleo.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'configuração fiscal do produto',
                'verbose_name_plural': 'configuração fiscal dos produtos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nfse', 'NFS-e (serviço)'), ('nfce', 'NFC-e (consumo)'), ('nfe', 'NF-e')], max_length=5, verbose_name='tipo')),
                ('natureza', models.CharField(choices=[('servico', 'Serviço'), ('consumo', 'Consumo')], max_length=10, verbose_name='natureza')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('autorizada', 'Autorizada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=12, verbose_name='status')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor (R$)')),
                ('referencia', models.CharField(blank=True, max_length=120, verbose_name='origem')),
                ('gateway', models.CharField(blank=True, max_length=20, verbose_name='gateway')),
                ('gateway_id', models.CharField(blank=True, max_length=80, verbose_name='id no gateway')),
                ('numero', models.CharField(blank=True, max_length=30, verbose_name='número')),
                ('serie', models.CharField(blank=True, max_length=10, verbose_name='série')),
                ('chave', models.CharField(blank=True, max_length=60, verbose_name='chave de acesso')),
                ('protocolo', models.CharField(blank=True, max_length=60, verbose_name='protocolo')),
                ('xml_url', models.URLField(blank=True, verbose_name='XML')),
                ('pdf_url', models.URLField(blank=True, verbose_name='PDF/DANFE')),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=255, verbose_name='motivo da rejeição')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('autorizada_em', models.DateTimeField(blank=True, null=True, verbose_name='autorizada em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to=settings.AUTH_USER_MODEL, verbose_name='emitido por')),
                ('tomador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='nucleo.pessoa', verbose_name='tomador/destinatário')),
            ],
            options={
                'verbose_name': 'documento fiscal',
                'verbose_name_plural': 'documentos fiscais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='evento')),
                ('detalhe', models.JSONField(blank=True, default=dict, verbose_name='detalhe')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='em')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='fiscal.documentofiscal', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'evento fiscal',
                'verbose_name_plural': 'eventos fiscais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
