# Generated by Django 6.0.6 on 2026-07-05 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0010_seed_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token público')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('metodo', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartão de crédito'), ('boleto', 'Boleto'), ('link', 'Link de pagamento')], max_length=8, verbose_name='método')),
                ('parcelas', models.PositiveSmallIntegerField(default=1, verbose_name='parcelas')),
                ('descricao', models.CharField(max_length=160, verbose_name='descrição')),
                ('finalidade', models.CharField(choices=[('sinal_reserva', 'Sinal de reserva'), ('saldo_conta', 'Saldo da conta'), ('avulso', 'Avulso')], default='avulso', max_length=14, verbose_name='finalidade')),
                ('reserva_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='reserva')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], default='pendente', max_length=10, verbose_name='status')),
                ('gateway', models.CharField(blank=True, max_length=30, verbose_name='gateway')),
                ('gateway_id', models.CharField(blank=True, max_length=80, verbose_name='id no gateway')),
                ('pix_copia_cola', models.TextField(blank=True, verbose_name='Pix copia-e-cola')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload do gateway')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='paga em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('pagador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='nucleo.pessoa', verbose_name='pagador')),
            ],
            options={
                'verbose_name': 'cobrança',
                'verbose_name_plural': 'cobranças',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criada', 'Criada'), ('paga', 'Paga'), ('estornada', 'Estornada'), ('cancelada', 'Cancelada'), ('webhook', 'Webhook')], max_length=10, verbose_name='tipo')),
                ('origem', models.CharField(blank=True, max_length=30, verbose_name='origem')),
                ('detalhe', models.JSONField(blank=True, default=dict, verbose_name='detalhe')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='em')),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pagamentos.cobranca', verbose_name='cobrança')),
            ],
            options={
                'verbose_name': 'evento de pagamento',
                'verbose_name_plural': 'eventos de pagamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
