# Generated by Django 6.0.7 on 2026-07-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='data_liquidacao',
            field=models.DateField(blank=True, null=True, verbose_name='data de liquidação'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='id_liquidacao',
            field=models.CharField(blank=True, max_length=80, verbose_name='id do depósito/lote'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='liquidado',
            field=models.BooleanField(default=False, verbose_name='liquidado no banco'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='taxa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='taxa da adquirente (R$)'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='valor_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor líquido (R$)'),
        ),
        migrations.AlterField(
            model_name='eventopagamento',
            name='tipo',
            field=models.CharField(choices=[('criada', 'Criada'), ('paga', 'Paga'), ('liquidada', 'Liquidada'), ('estornada', 'Estornada'), ('cancelada', 'Cancelada'), ('webhook', 'Webhook')], max_length=10, verbose_name='tipo'),
        ),
    ]
