# Generated by Django 6.0.7 on 2026-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_cobranca_data_liquidacao_cobranca_id_liquidacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='grupo_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='grupo (reserva-mãe)'),
        ),
    ]
