# Generated by Django 6.0.7 on 2026-09-20 16:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0014_campanhaemail_envioemail_campanha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetos', models.JSONField(blank=True, default=dict, verbose_name='tetos por mês')),
                ('alerta_pct', models.PositiveSmallIntegerField(default=80, verbose_name='alerta em (% do teto)')),
            ],
            options={
                'verbose_name': 'verba de marketing',
                'verbose_name_plural': 'verba de marketing',
            },
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='nome')),
                ('objetivo', models.TextField(blank=True, verbose_name='objetivo')),
                ('publico', models.CharField(blank=True, max_length=140, verbose_name='público-alvo')),
                ('canais', models.JSONField(blank=True, default=list, verbose_name='canais')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('fase', models.CharField(choices=[('ideia', 'Ideia'), ('proposta', 'Proposta'), ('aprovacao', 'Aprovação'), ('estruturacao', 'Estruturação'), ('producao', 'Produção'), ('noar', 'No ar'), ('encerrada', 'Encerrada')], default='ideia', max_length=14, verbose_name='fase')),
                ('fornecedor', models.CharField(blank=True, max_length=140, verbose_name='fornecedor externo')),
                ('verba_prevista', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='verba prevista (R$)')),
                ('verba_travada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Travada no teto do mês ao aprovar; devolvida (não gasta) ao encerrar.', max_digits=10, verbose_name='verba travada (R$)')),
                ('aprovada_em', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('retro_funcionou', models.TextField(blank=True, verbose_name='retrospectiva — o que funcionou')),
                ('retro_nao', models.TextField(blank=True, verbose_name='retrospectiva — o que não funcionou')),
                ('retro_diferente', models.TextField(blank=True, verbose_name='retrospectiva — o que fazer diferente')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('anuncio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluxo', to='comercial.campanha', verbose_name='campanha de anúncio (origem)')),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_mkt_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('criativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_mkt_criativo', to=settings.AUTH_USER_MODEL, verbose_name='criação')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_mkt_sob', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_mkt_pedidas', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'campanha de marketing',
                'verbose_name_plural': 'campanhas de marketing',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='texto')),
                ('em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_mkt', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversa', to='marketing.campanha', verbose_name='campanha')),
            ],
            options={
                'verbose_name': 'comentário',
                'verbose_name_plural': 'comentários',
                'ordering': ['em'],
            },
        ),
        migrations.CreateModel(
            name='EtapaCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='tarefa')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('feito', models.BooleanField(default=False, verbose_name='feito')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='marketing.campanha', verbose_name='campanha')),
                ('dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_mkt', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'etapa de campanha',
                'verbose_name_plural': 'etapas de campanha',
                'ordering': ['feito', 'prazo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PecaCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='nome')),
                ('canal', models.CharField(blank=True, max_length=40, verbose_name='canal')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('status', models.CharField(choices=[('a_fazer', 'A fazer'), ('em_producao', 'Em produção'), ('pronta', 'Pronta')], default='a_fazer', max_length=14, verbose_name='status')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='marketing.campanha', verbose_name='campanha')),
            ],
            options={
                'verbose_name': 'peça de campanha',
                'verbose_name_plural': 'peças de campanha',
                'ordering': ['data', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=40, verbose_name='critério')),
                ('feito', models.BooleanField(default=False, verbose_name='cumprido')),
                ('em', models.DateTimeField(blank=True, null=True, verbose_name='marcado em')),
                ('dispensado', models.BooleanField(default=False, verbose_name='dispensado')),
                ('motivo_dispensa', models.CharField(blank=True, max_length=200, verbose_name='motivo da dispensa')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='marketing.campanha', verbose_name='campanha')),
                ('por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks_mkt', to=settings.AUTH_USER_MODEL, verbose_name='marcado por')),
            ],
            options={
                'verbose_name': 'item de checklist',
                'verbose_name_plural': 'itens de checklist',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('campanha', 'chave'), name='check_unico_por_campanha')],
            },
        ),
    ]
