# Generated by Django 6.0.7 on 2026-09-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_seed_e_ativar'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Alguns itens só fecham com um arquivo anexado (referência, briefing, arte).', null=True, upload_to='marketing/checklist/', verbose_name='evidência (anexo)'),
        ),
    ]
