# Generated by Django 6.0.7 on 2026-09-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_itemchecklist_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='nota',
            field=models.CharField(blank=True, help_text='Observação livre do responsável (opcional) — ex.: a base da verba.', max_length=280, verbose_name='nota'),
        ),
    ]
