# Generated by Django 6.0.7 on 2026-09-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_itemchecklist_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='etapa_funil',
            field=models.CharField(blank=True, choices=[('topo', 'Topo (descoberta)'), ('meio', 'Meio (consideração)'), ('fundo', 'Fundo (conversão)')], max_length=5, verbose_name='etapa de funil'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='meta_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='meta'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='objetivo_tipo',
            field=models.CharField(blank=True, choices=[('leads', 'Leads'), ('seguidores', 'Seguidores'), ('engajamento', 'Engajamento'), ('alcance', 'Alcance'), ('trafego', 'Tráfego (cliques)'), ('vendas', 'Vendas / Reservas'), ('outro', 'Outro')], max_length=12, verbose_name='tipo de objetivo'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='realizado_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resultado alcançado (manual por enquanto).', max_digits=12, null=True, verbose_name='realizado'),
        ),
    ]
