# Generated by Django 6.0.8 on 2026-10-05 15:24

import apps.marketing.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_campanha_etapa_funil_campanha_meta_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchecklist',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Alguns itens só fecham com um arquivo anexado (referência, briefing, arte).', null=True, upload_to='marketing/checklist/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp', 'gif', 'doc', 'docx', 'xls', 'xlsx', 'csv']), apps.marketing.models.validar_tamanho_anexo], verbose_name='evidência (anexo)'),
        ),
    ]
