# Generated by Django 6.0.6 on 2026-07-05 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0010_seed_almoxarifado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLimpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('limpa', 'Limpa'), ('suja', 'Suja'), ('em_limpeza', 'Em limpeza'), ('inspecionada', 'Inspecionada')], default='limpa', max_length=12, verbose_name='situação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('uh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limpeza', to='nucleo.uh', verbose_name='quarto')),
            ],
            options={
                'verbose_name': 'status de limpeza',
                'verbose_name_plural': 'status de limpeza',
            },
        ),
        migrations.CreateModel(
            name='TarefaGovernanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('faxina_completa', 'Faxina completa'), ('arrumacao', 'Arrumação'), ('troca_roupa', 'Troca de roupa de cama'), ('pos_manutencao', 'Pós-manutenção')], default='faxina_completa', max_length=16, verbose_name='tipo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=12, verbose_name='status')),
                ('origem', models.CharField(default='manual', max_length=20, verbose_name='origem')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('gerada_em', models.DateTimeField(auto_now_add=True, verbose_name='gerada em')),
                ('iniciada_em', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('camareira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faxinas', to=settings.AUTH_USER_MODEL, verbose_name='camareira')),
                ('uh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_governanca', to='nucleo.uh', verbose_name='quarto')),
            ],
            options={
                'verbose_name': 'tarefa de governança',
                'verbose_name_plural': 'tarefas de governança',
                'ordering': ['status', 'gerada_em'],
            },
        ),
    ]
