# Generated by Django 6.0.7 on 2026-08-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslimpeza',
            name='situacao',
            field=models.CharField(choices=[('limpa', 'Limpo'), ('suja', 'Sujo'), ('em_limpeza', 'Em limpeza'), ('inspecionada', 'Inspecionado')], default='limpa', max_length=12, verbose_name='situação'),
        ),
    ]
