from django.urls import path

from . import views

app_name = "comercial"

urlpatterns = [
    path("", views.funil, name="funil"),
    path("cacador/", views.cacador, name="cacador"),
    path("cacador/<int:pk>/feedback/", views.cacador_feedback, name="cacador_feedback"),
    path("instagram/", views.instagram, name="instagram"),
    path("painel/", views.painel, name="painel"),
    path("painel/meta/", views.meta, name="meta"),
    path("tarefas/", views.tarefas, name="tarefas"),
    path("paginas/", views.paginas, name="paginas"),
    path("paginas/nova/", views.pagina_nova, name="pagina_nova"),
    path("paginas/<int:pk>/", views.pagina_detalhe, name="pagina_detalhe"),
    path("paginas/<int:pk>/editar/", views.pagina_editar, name="pagina_editar"),
    path("paginas/<int:pk>/status/", views.pagina_status, name="pagina_status"),
    path("paginas/<int:pk>/qr/", views.pagina_qr, name="pagina_qr"),
    path("impulsionamento/", views.impulsionamento, name="impulsionamento"),
    path("impulsionamento/nova/", views.campanha_nova, name="campanha_nova"),
    path("impulsionamento/<int:pk>/", views.campanha_detalhe, name="campanha_detalhe"),
    path("impulsionamento/<int:pk>/editar/", views.campanha_editar, name="campanha_editar"),
    path("impulsionamento/<int:pk>/gasto/", views.campanha_gasto, name="campanha_gasto"),
    path("impulsionamento/<int:pk>/sincronizar/", views.campanha_sincronizar, name="campanha_sincronizar"),
    path("nova/", views.nova, name="nova"),
    path("lead-novo/", views.lead_novo, name="lead_novo"),
    path("<int:pk>/", views.oportunidade, name="oportunidade"),
    path("<int:pk>/mover/", views.mover, name="mover"),
    path("<int:pk>/assumir/", views.assumir, name="assumir"),
    path("<int:pk>/conversao/", views.conversao_reenviar, name="conversao_reenviar"),
    path("<int:pk>/proposta-sinal/", views.enviar_proposta_sinal, name="enviar_proposta_sinal"),
    path("<int:pk>/email/", views.enviar_email_lead, name="enviar_email_lead"),
    path("email/templates/", views.email_templates, name="email_templates"),
    path("email/templates/novo/", views.email_template_novo, name="email_template_novo"),
    path("email/templates/<int:pk>/editar/", views.email_template_editar, name="email_template_editar"),
    path("email/templates/<int:pk>/excluir/", views.email_template_excluir, name="email_template_excluir"),
    path("<int:pk>/whatsapp/enviar/", views.whatsapp_enviar, name="whatsapp_enviar"),
    path("<int:pk>/whatsapp/simular/", views.whatsapp_simular, name="whatsapp_simular"),
    path("respostas/", views.respostas, name="respostas"),
    path("respostas/nova/", views.resposta_nova, name="resposta_nova"),
    path("respostas/<int:pk>/editar/", views.resposta_editar, name="resposta_editar"),
    path("respostas/<int:pk>/excluir/", views.resposta_excluir, name="resposta_excluir"),
    path("<int:pk>/atividade/", views.atividade, name="atividade"),
    path("<int:pk>/cotar/", views.cotar, name="cotar"),
    path("<int:pk>/converter/", views.converter, name="converter"),
    path("<int:pk>/perder/", views.perder, name="perder"),
    path("tarefa/<int:pk>/concluir/", views.concluir_tarefa, name="concluir_tarefa"),
]
