# Generated by Django 6.0.6 on 2026-07-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_seed_modulos_fase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modulos',
            field=models.ManyToManyField(blank=True, help_text='Módulos que este usuário pode acessar. Superusuários acessam todos os módulos ativos.', related_name='usuarios', to='nucleo.modulocontratado', verbose_name='módulos com acesso'),
        ),
    ]
