# Generated by Django 6.0.6 on 2026-07-04 13:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_usuario_modulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_debito', 'Cartão de débito'), ('cartao_credito', 'Cartão de crédito'), ('transferencia', 'Transferência'), ('cortesia', 'Cortesia')], max_length=15, verbose_name='tipo')),
                ('permite_parcelamento', models.BooleanField(default=False, verbose_name='permite parcelamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'forma de pagamento',
                'verbose_name_plural': 'formas de pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('documento', models.CharField(blank=True, help_text='CPF ou CNPJ, com ou sem pontuação.', max_length=18, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('classificacao', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('super_alta', 'Super alta'), ('feriado', 'Feriado')], max_length=12, verbose_name='classificação')),
                ('inicio', models.DateField(verbose_name='início')),
                ('fim', models.DateField(verbose_name='fim')),
            ],
            options={
                'verbose_name': 'temporada',
                'verbose_name_plural': 'temporadas',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoUH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('capacidade', models.PositiveSmallIntegerField(default=2, verbose_name='capacidade (pessoas)')),
                ('tarifa_base', models.DecimalField(decimal_places=2, help_text='Diária de referência; temporadas e acordos ajustam sobre ela.', max_digits=10, verbose_name='tarifa base (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'tipo de UH',
                'verbose_name_plural': 'tipos de UH',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=8, verbose_name='tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria financeira',
                'verbose_name_plural': 'categorias financeiras',
                'ordering': ['tipo', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'tipo'), name='categoria_unica_por_tipo')],
            },
        ),
        migrations.CreateModel(
            name='EntradaLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='ocorrência')),
                ('importante', models.BooleanField(default=False, help_text='Destaca a entrada para o próximo turno.', verbose_name='importante')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrada em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_logbook', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'entrada do logbook',
                'verbose_name_plural': 'entradas do logbook',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=8, verbose_name='tipo')),
                ('centro', models.CharField(default='nucleo', help_text='Módulo de origem do lançamento.', max_length=20, verbose_name='centro de receita/custo')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor (R$)')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de competência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='nucleo.categoriafinanceira', verbose_name='categoria')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'lançamento financeiro',
                'verbose_name_plural': 'lançamentos financeiros',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('nacionalidade', models.CharField(blank=True, default='Brasileira', max_length=60, verbose_name='nacionalidade')),
                ('preferencias', models.TextField(blank=True, help_text='Preferências do hóspede: quarto, travesseiro, restrições etc.', verbose_name='preferências')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospede', to='nucleo.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'hóspede',
                'verbose_name_plural': 'hóspedes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=80, verbose_name='cargo')),
                ('setor', models.CharField(blank=True, max_length=80, verbose_name='setor')),
                ('admissao', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('usuario', models.OneToOneField(blank=True, help_text='Login deste funcionário no CRM, se tiver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='usuário do sistema')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='nucleo.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(blank=True, help_text='Ex.: hortifrúti, bebidas, lavanderia industrial.', max_length=100, verbose_name='ramo de atividade')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to='nucleo.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
            },
        ),
        migrations.CreateModel(
            name='ContaPagarReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pagar', 'A pagar'), ('receber', 'A receber')], max_length=8, verbose_name='tipo')),
                ('centro', models.CharField(default='nucleo', max_length=20, verbose_name='centro de receita/custo')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor (R$)')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('baixada', 'Baixada'), ('cancelada', 'Cancelada')], default='aberta', max_length=10, verbose_name='status')),
                ('baixada_em', models.DateField(blank=True, null=True, verbose_name='baixada em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('baixada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_baixadas', to=settings.AUTH_USER_MODEL, verbose_name='baixada por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='nucleo.categoriafinanceira', verbose_name='categoria')),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conta', to='nucleo.lancamentofinanceiro', verbose_name='lançamento da baixa')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='nucleo.pessoa', verbose_name='fornecedor/cliente')),
            ],
            options={
                'verbose_name': 'conta a pagar/receber',
                'verbose_name_plural': 'contas a pagar/receber',
                'ordering': ['status', 'vencimento'],
            },
        ),
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=20, verbose_name='módulo (centro)')),
                ('fundo_troco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='fundo de troco (R$)')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=10, verbose_name='status')),
                ('aberta_em', models.DateTimeField(auto_now_add=True, verbose_name='aberta em')),
                ('fechada_em', models.DateTimeField(blank=True, null=True, verbose_name='fechada em')),
                ('valor_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='dinheiro contado no fechamento (R$)')),
                ('diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='diferença (contado − esperado)')),
                ('observacoes_fechamento', models.TextField(blank=True, verbose_name='observações do fechamento')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
            ],
            options={
                'verbose_name': 'sessão de caixa',
                'verbose_name_plural': 'sessões de caixa',
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recebimento', 'Recebimento'), ('reforco', 'Reforço'), ('sangria', 'Sangria'), ('estorno', 'Estorno')], max_length=12, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor (R$)')),
                ('parcelas', models.PositiveSmallIntegerField(default=1, verbose_name='parcelas')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('motivo', models.TextField(blank=True, help_text='Obrigatório em estornos.', verbose_name='motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('forma_pagamento', models.ForeignKey(blank=True, help_text='Obrigatória em recebimentos e estornos; reforço e sangria são dinheiro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='nucleo.formapagamento', verbose_name='forma de pagamento')),
                ('movimento_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estornos', to='nucleo.movimentocaixa', verbose_name='movimento original')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='nucleo.sessaocaixa', verbose_name='sessão')),
            ],
            options={
                'verbose_name': 'movimento de caixa',
                'verbose_name_plural': 'movimentos de caixa',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TrilhaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=40, verbose_name='ação')),
                ('alvo', models.CharField(max_length=80, verbose_name='alvo')),
                ('alvo_id', models.CharField(max_length=40, verbose_name='id do alvo')),
                ('detalhe', models.JSONField(blank=True, default=dict, verbose_name='detalhe')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='em')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'trilha de auditoria',
                'verbose_name_plural': 'trilhas de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='número/nome')),
                ('bloco', models.CharField(blank=True, max_length=40, verbose_name='bloco/área')),
                ('andar', models.CharField(blank=True, max_length=20, verbose_name='andar')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('bloqueada', 'Bloqueada'), ('inativa', 'Inativa')], default='ativa', max_length=10, verbose_name='status operacional')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhs', to='nucleo.tipouh', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'UH',
                'verbose_name_plural': 'UHs',
                'ordering': ['numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aberta')), fields=('operador', 'modulo'), name='uma_sessao_aberta_por_operador_modulo'),
        ),
        migrations.AddConstraint(
            model_name='movimentocaixa',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='movimento_caixa_valor_positivo'),
        ),
    ]
