# Generated by Django 6.0.6 on 2026-07-04 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_seed_formas_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[('fisica', 'Pessoa física'), ('juridica', 'Pessoa jurídica')], default='fisica', max_length=8, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('agencia', 'Agência de viagens'), ('empresa', 'Empresa')], default='agencia', max_length=8, verbose_name='categoria')),
                ('comissao_padrao', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de comissão sobre reservas faturadas para esta agência.', max_digits=5, verbose_name='comissão padrão (%)')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agencia', to='nucleo.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'agência/empresa',
                'verbose_name_plural': 'agências/empresas',
            },
        ),
    ]
