# Generated by Django 6.0.6 on 2026-07-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_backfill_tipo_pessoa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradalogbook',
            options={'ordering': ['-criado_em'], 'verbose_name': 'ocorrência', 'verbose_name_plural': 'ocorrências'},
        ),
        migrations.AlterModelOptions(
            name='tipouh',
            options={'ordering': ['nome'], 'verbose_name': 'tipo de quarto', 'verbose_name_plural': 'tipos de quarto'},
        ),
        migrations.AlterModelOptions(
            name='uh',
            options={'ordering': ['numero'], 'verbose_name': 'quarto', 'verbose_name_plural': 'quartos'},
        ),
    ]
