# Generated by Django 6.0.6 on 2026-07-04 22:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_alter_entradalogbook_options_alter_tipouh_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria de produto',
                'verbose_name_plural': 'categorias de produto',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('modulo', models.CharField(default='nucleo', help_text='Módulo dono deste depósito (almoxarifado central = Núcleo).', max_length=20, verbose_name='vínculo (centro)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'local de estoque',
                'verbose_name_plural': 'locais de estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberto', 'Em contagem'), ('aplicado', 'Aplicado'), ('cancelado', 'Cancelado')], default='aberto', max_length=10, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='aberto em')),
                ('aplicado_em', models.DateTimeField(blank=True, null=True, verbose_name='aplicado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='nucleo.localestoque', verbose_name='local')),
            ],
            options={
                'verbose_name': 'inventário',
                'verbose_name_plural': 'inventários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='código de barras')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('unidade', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilo'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('cx', 'Caixa'), ('pct', 'Pacote'), ('dz', 'Dúzia')], default='un', max_length=4, verbose_name='unidade')),
                ('natureza', models.CharField(choices=[('servico', 'Serviço'), ('consumo', 'Consumo')], default='consumo', help_text='Produto físico é consumo (NF-e/NFC-e). Sem default silencioso.', max_length=10, verbose_name='natureza fiscal')),
                ('custo_medio', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Calculado pelo sistema a cada entrada — não editar à mão.', max_digits=12, verbose_name='custo médio (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='preço de venda (R$)')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Abaixo disso, o produto entra nos alertas do painel.', max_digits=12, verbose_name='estoque mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='nucleo.categoriaproduto', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada_compra', 'Entrada por compra'), ('saida_venda', 'Saída por venda'), ('consumo_interno', 'Consumo interno'), ('perda', 'Perda/quebra/vencimento'), ('transf_saida', 'Transferência (saída)'), ('transf_entrada', 'Transferência (entrada)'), ('ajuste', 'Ajuste de inventário')], max_length=16, verbose_name='tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade (sinalizada)')),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='custo unitário (R$)')),
                ('documento', models.CharField(blank=True, help_text='Nota fiscal, comanda, ordem — de onde veio o movimento.', max_length=80, verbose_name='documento de origem')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='nucleo.localestoque', verbose_name='local')),
                ('transferencia_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='par', to='nucleo.movimentoestoque', verbose_name='par da transferência')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='nucleo.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'movimento de estoque',
                'verbose_name_plural': 'movimentos de estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_sistema', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='saldo do sistema')),
                ('quantidade_contada', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='quantidade contada')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nucleo.inventario', verbose_name='inventário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='nucleo.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item de inventário',
                'verbose_name_plural': 'itens de inventário',
                'constraints': [models.UniqueConstraint(fields=('inventario', 'produto'), name='item_unico_por_inventario')],
            },
        ),
    ]
