# Generated by Django 6.0.6 on 2026-07-07 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0012_alter_modulocontratado_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='em prospecção desde')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prospecto', to='nucleo.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'prospecto',
                'verbose_name_plural': 'prospecção',
            },
        ),
    ]
