# Generated by Django 6.0.7 on 2026-07-16 20:13

from django.db import migrations, models


def marcar_pcd(apps, schema_editor):
    UH = apps.get_model("nucleo", "UH")
    UH.objects.filter(numero__in=["Quarto 04", "Quarto 14"]).update(pcd=True)


def desmarcar_pcd(apps, schema_editor):
    UH = apps.get_model("nucleo", "UH")
    UH.objects.filter(numero__in=["Quarto 04", "Quarto 14"]).update(pcd=False)


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0013_prospecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='uh',
            name='pcd',
            field=models.BooleanField(default=False, help_text='Quarto adaptado para pessoa com deficiência.', verbose_name='acessível (PCD)'),
        ),
        migrations.RunPython(marcar_pcd, desmarcar_pcd),
    ]
