# Generated by Django 6.0.7 on 2026-08-07 13:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0015_tipouh_modalidade_day_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoUH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_sofa_cama', models.BooleanField(default=False, verbose_name='tem sofá-cama')),
                ('sofa_adultos', models.PositiveSmallIntegerField(default=1, verbose_name='sofá: adultos')),
                ('sofa_criancas', models.PositiveSmallIntegerField(default=2, verbose_name='sofá: crianças')),
                ('sofa_idade_maxima', models.PositiveSmallIntegerField(default=15, verbose_name='sofá: idade máxima das crianças')),
                ('max_colchoes_extras', models.PositiveSmallIntegerField(default=0, verbose_name='máximo de colchões extras')),
                ('tarifa_colchao_extra', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=10, verbose_name='tarifa do colchão extra (R$)')),
                ('uh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='nucleo.uh', verbose_name='quarto')),
            ],
            options={
                'verbose_name': 'configuração do quarto',
                'verbose_name_plural': 'configurações dos quartos',
            },
        ),
        migrations.CreateModel(
            name='PosicaoCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: «Quarto 1», «Quarto 2», «Suíte».', max_length=40, verbose_name='nome')),
                ('montagem_padrao', models.CharField(choices=[('casal', '1 cama de casal'), ('dois_solteiros', '2 camas de solteiro')], default='casal', max_length=14, verbose_name='montagem padrão')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('uh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_cama', to='nucleo.uh', verbose_name='quarto')),
            ],
            options={
                'verbose_name': 'posição de cama',
                'verbose_name_plural': 'posições de cama',
                'ordering': ['uh', 'ordem'],
            },
        ),
    ]
