# Generated by Django 6.0.7 on 2026-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0017_seed_camas_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='uh',
            name='tarifa_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diária fixa desta unidade; vence o cálculo por tipo/temporada. Em branco = usa a tarifa do tipo (com acréscimo se for de dois cômodos).', max_digits=10, null=True, verbose_name='tarifa própria (R$)'),
        ),
    ]
