# Generated by Django 6.0.7 on 2026-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0018_uh_tarifa_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='areas',
            field=models.JSONField(blank=True, default=list, help_text='Áreas do núcleo concedidas (Quartos, Financeiro, Equipe…). Gerido em Equipe & Acessos. Superusuário acessa tudo.', verbose_name='áreas-core com acesso'),
        ),
    ]
