# Generated by Django 6.0.7 on 2026-08-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0020_seed_areas_gerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilhaauditoria',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AddIndex(
            model_name='trilhaauditoria',
            index=models.Index(fields=['-criado_em'], name='nucleo_tril_criado__e96578_idx'),
        ),
        migrations.AddIndex(
            model_name='trilhaauditoria',
            index=models.Index(fields=['usuario', '-criado_em'], name='nucleo_tril_usuario_21b9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='trilhaauditoria',
            index=models.Index(fields=['alvo', 'alvo_id'], name='nucleo_tril_alvo_73ac51_idx'),
        ),
    ]
