# Generated by Django 6.0.7 on 2026-08-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0022_seed_area_caixa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['pessoa__nome'], 'verbose_name': 'funcionário', 'verbose_name_plural': 'funcionários'},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='carga_semanal',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='carga semanal (h)'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='expediente_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='fim do expediente'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='expediente_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='início do expediente'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='intervalo_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='fim do intervalo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='intervalo_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='início do intervalo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='salário base (R$)'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='turno',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], max_length=10, verbose_name='turno'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='vinculo',
            field=models.CharField(blank=True, choices=[('clt', 'CLT'), ('pj', 'PJ'), ('temporario', 'Temporário'), ('estagio', 'Estágio'), ('diarista', 'Diarista')], max_length=12, verbose_name='vínculo'),
        ),
    ]
