# Generated by Django 6.0.7 on 2026-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0024_seed_funcionarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='uh',
            name='aceita_pet',
            field=models.BooleanField(default=False, verbose_name='aceita pet'),
        ),
        migrations.AddField(
            model_name='uh',
            name='ar_condicionado',
            field=models.BooleanField(default=False, verbose_name='ar-condicionado'),
        ),
        migrations.AddField(
            model_name='uh',
            name='diferenciais',
            field=models.TextField(blank=True, help_text='Destaques livres do quarto (ex.: rede na varanda, banheira NÃO).', verbose_name='diferenciais'),
        ),
        migrations.AddField(
            model_name='uh',
            name='nome_tematico',
            field=models.CharField(blank=True, help_text='Ex.: Oficina do Relojoeiro. Aparece na vitrine do site.', max_length=60, verbose_name='nome temático'),
        ),
        migrations.AddField(
            model_name='uh',
            name='tipo_cama',
            field=models.CharField(blank=True, choices=[('casal', 'Casal'), ('queen', 'Casal queen'), ('king', 'Casal king'), ('2solteiros', 'Dois solteiros'), ('misto', 'Casal + solteiro')], max_length=12, verbose_name='tipo de cama'),
        ),
        migrations.AddField(
            model_name='uh',
            name='varanda',
            field=models.BooleanField(default=False, verbose_name='varanda'),
        ),
        migrations.AddField(
            model_name='uh',
            name='vista_lago',
            field=models.BooleanField(default=False, verbose_name='vista para o lago'),
        ),
        migrations.AlterField(
            model_name='uh',
            name='numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='número'),
        ),
    ]
