# Generated by Django 6.0.7 on 2026-08-24 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0025_uh_aceita_pet_uh_ar_condicionado_uh_diferenciais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradalogbook',
            name='resolucao_nota',
            field=models.CharField(blank=True, max_length=280, verbose_name='como foi resolvida'),
        ),
        migrations.AddField(
            model_name='entradalogbook',
            name='resolvida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='resolvida em'),
        ),
        migrations.AddField(
            model_name='entradalogbook',
            name='resolvida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logbook_resolvidas', to=settings.AUTH_USER_MODEL, verbose_name='resolvida por'),
        ),
        migrations.AddField(
            model_name='entradalogbook',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('resolvida', 'Resolvida')], default='aberta', max_length=20, verbose_name='situação'),
        ),
        migrations.CreateModel(
            name='ComentarioLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='resposta')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='respondido em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios_logbook', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='nucleo.entradalogbook', verbose_name='ocorrência')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
                'ordering': ['criado_em'],
            },
        ),
    ]
