# Generated by Django 6.0.7 on 2026-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0029_aposentar_modulo_frigobar'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='compensacao_feriado',
            field=models.CharField(choices=[('folga', 'Folga compensatória'), ('dobro', 'Pagamento em dobro')], default='folga', max_length=6, verbose_name='feriado trabalhado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='regime_horas',
            field=models.CharField(choices=[('banco', 'Banco de horas'), ('extra', 'Hora extra')], default='banco', max_length=6, verbose_name='excedente de jornada'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], help_text='Regra de domingo na escala: ♀ folga 2 de 4, ♂ folga 1 de 4.', max_length=1, verbose_name='sexo'),
        ),
    ]
