# Generated by Django 6.0.7 on 2026-09-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0032_pessoa_email_marketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='autorizacao',
            field=models.CharField(blank=True, help_text='Código de autorização ou NSU do comprovante do cartão — para conciliar com a maquininha (SafraPay).', max_length=40, verbose_name='autorização / NSU'),
        ),
    ]
