# Generated by Django 6.0.7 on 2026-09-10 21:01

from django.db import migrations, models


def backfill_optin_whatsapp(apps, schema_editor):
    """Quem já deu opt-in de e-mail pela LP consentiu 'e-mail E WhatsApp' (texto da
    LP). Reaproveita esse consentimento para o novo canal, herdando a data."""
    from django.db.models import F

    Pessoa = apps.get_model("nucleo", "Pessoa")
    Pessoa.objects.filter(aceita_email=True).update(
        aceita_whatsapp=True, whatsapp_optin_em=F("email_optin_em"))


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0033_movimentocaixa_autorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='aceita_whatsapp',
            field=models.BooleanField(default=False, verbose_name='aceita WhatsApp'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='whatsapp_optin_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='opt-in de WhatsApp em'),
        ),
        migrations.RunPython(backfill_optin_whatsapp, migrations.RunPython.noop),
    ]
