# Generated by Django 6.0.7 on 2026-10-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0034_pessoa_aceita_whatsapp_pessoa_whatsapp_optin_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulocontratado',
            name='codigo',
            field=models.CharField(choices=[('reservas', 'Reservas'), ('governanca', 'Governança'), ('manutencao', 'Manutenção'), ('escala', 'Escala'), ('estoque', 'Estoque'), ('loja', 'Loja'), ('restaurante', 'Restaurante Piscina'), ('lavanderia', 'Lavanderia'), ('frigobar', 'Frigobar'), ('pagamentos', 'Pagamentos Online'), ('appsite', 'APP/Site'), ('crm_hospede', 'CRM do Hóspede'), ('canais', 'Canais/OTAs'), ('fiscal', 'Fiscal'), ('auditoria', 'Auditoria'), ('relatorios', 'Relatórios'), ('comercial', 'Comercial'), ('marketing', 'Marketing')], max_length=20, unique=True, verbose_name='módulo'),
        ),
    ]
