# Generated by Django 6.0.6 on 2026-07-07 20:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0012_alter_modulocontratado_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaFunil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('probabilidade', models.PositiveSmallIntegerField(default=0, help_text='Chance de fechar nesta etapa — usada na previsão ponderada.', verbose_name='probabilidade (%)')),
                ('tipo', models.CharField(choices=[('aberta', 'Em aberto'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], default='aberta', max_length=10, verbose_name='tipo')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'etapa do funil',
                'verbose_name_plural': 'etapas do funil',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MotivoPerda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='motivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'motivo de perda',
                'verbose_name_plural': 'motivos de perda',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('faturamento', models.CharField(choices=[('particular', 'Particular (B2C)'), ('agencia', 'Agência (B2B)'), ('empresa', 'Empresa (B2B)')], default='particular', max_length=12, verbose_name='faturamento')),
                ('origem', models.CharField(choices=[('site', 'Site'), ('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('indicacao', 'Indicação'), ('agencia', 'Agência/OTA'), ('presencial', 'Presencial'), ('outro', 'Outro')], default='outro', max_length=12, verbose_name='origem')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor estimado (R$)')),
                ('checkin_previsto', models.DateField(blank=True, null=True, verbose_name='check-in previsto')),
                ('checkout_previsto', models.DateField(blank=True, null=True, verbose_name='check-out previsto')),
                ('quartos', models.PositiveSmallIntegerField(default=1, verbose_name='quartos')),
                ('hospedes', models.PositiveSmallIntegerField(default=2, verbose_name='hóspedes')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('ganha', 'Ganha'), ('perdida', 'Perdida')], default='aberta', max_length=10, verbose_name='status')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('reserva_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='reserva vinculada')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('fechado_em', models.DateTimeField(blank=True, null=True, verbose_name='fechada em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='comercial.etapafunil', verbose_name='etapa')),
                ('motivo_perda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='comercial.motivoperda', verbose_name='motivo da perda')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='nucleo.pessoa', verbose_name='lead (pessoa/agência/empresa)')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'oportunidade',
                'verbose_name_plural': 'oportunidades',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('reuniao', 'Reunião'), ('nota', 'Nota'), ('tarefa', 'Tarefa')], default='nota', max_length=10, verbose_name='tipo')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('quando', models.DateTimeField(verbose_name='quando')),
                ('concluida', models.BooleanField(default=True, help_text='Desmarcada = tarefa/follow-up agendado ainda por fazer.', verbose_name='concluída')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrada em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_comerciais', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='comercial.oportunidade', verbose_name='oportunidade')),
            ],
            options={
                'verbose_name': 'atividade comercial',
                'verbose_name_plural': 'atividades comerciais',
                'ordering': ['-quando'],
            },
        ),
    ]
