# Generated by Django 6.0.7 on 2026-07-17 13:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_seed_e_ativar'),
        ('nucleo', '0014_uh_pcd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Use o 1º dia do mês.', unique=True, verbose_name='mês')),
                ('valor_meta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='meta de receita (R$)')),
                ('oportunidades_meta', models.PositiveIntegerField(default=0, verbose_name='meta de ganhos (qtd)')),
            ],
            options={
                'verbose_name': 'meta comercial',
                'verbose_name_plural': 'metas comerciais',
                'ordering': ['-mes'],
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='cobranca_sinal_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='cobrança de sinal'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='nps_convidado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='NPS convidado em'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–100: valor + datas + origem + engajamento.', verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='atividadecomercial',
            name='tipo',
            field=models.CharField(choices=[('ligacao', 'Ligação'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('reuniao', 'Reunião'), ('nota', 'Nota'), ('tarefa', 'Tarefa'), ('cotacao', 'Cotação'), ('sistema', 'Sistema')], default='nota', max_length=10, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='check-in')),
                ('checkout', models.DateField(verbose_name='check-out')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='diária (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total estimado (R$)')),
                ('validade', models.DateField(verbose_name='válida até')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='comercial.oportunidade', verbose_name='oportunidade')),
                ('tipo_uh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_comerciais', to='nucleo.tipouh', verbose_name='tipo de quarto')),
            ],
            options={
                'verbose_name': 'cotação',
                'verbose_name_plural': 'cotações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PermanenciaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(verbose_name='entrou em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='saiu em')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanencias', to='comercial.etapafunil', verbose_name='etapa')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanencias', to='comercial.oportunidade', verbose_name='oportunidade')),
            ],
            options={
                'verbose_name': 'permanência em etapa',
                'verbose_name_plural': 'permanências em etapa',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
