# Generated by Django 6.0.7 on 2026-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_plano_p0_p3'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='tipo_interesse',
            field=models.CharField(choices=[('hospedagem', 'Hospedagem'), ('evento', 'Evento / confraternização'), ('day_use', 'Dia na Pousada'), ('outro', 'Outro')], default='hospedagem', max_length=12, verbose_name='tipo de interesse'),
        ),
    ]
