# Generated by Django 6.0.7 on 2026-07-28 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_tipo_interesse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(choices=[('quente', 'Quente'), ('morno', 'Morno'), ('frio', 'Frio')], default='frio', max_length=6, verbose_name='temperatura')),
                ('motivos', models.JSONField(blank=True, default=list, verbose_name='motivos do score')),
                ('sinais', models.JSONField(blank=True, default=dict, verbose_name='sinais extraídos')),
                ('rascunho', models.TextField(blank=True, verbose_name='rascunho do próximo passo')),
                ('util', models.BooleanField(blank=True, null=True, verbose_name='útil?')),
                ('revisado_em', models.DateTimeField(blank=True, null=True, verbose_name='revisado em')),
                ('gerado_em', models.DateTimeField(auto_now=True, verbose_name='analisado em')),
                ('oportunidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='comercial.oportunidade', verbose_name='oportunidade')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
            ],
            options={
                'verbose_name': 'análise de lead',
                'verbose_name_plural': 'análises de leads',
            },
        ),
    ]
