# Generated by Django 6.0.7 on 2026-08-31 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_analiselead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaCaptacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome (interno)')),
                ('slug', models.SlugField(help_text='Vira a URL pública: /captacao/<slug>/', max_length=60, unique=True, verbose_name='endereço (slug)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('encerrada', 'Encerrada')], default='rascunho', max_length=10, verbose_name='status')),
                ('tema', models.CharField(choices=[('fundador', 'Fundador (inauguração)')], default='fundador', max_length=12, verbose_name='modelo visual')),
                ('tipo_interesse', models.CharField(choices=[('hospedagem', 'Hospedagem'), ('evento', 'Evento / confraternização'), ('day_use', 'Dia na Pousada'), ('outro', 'Outro')], default='hospedagem', help_text='Tipo de interesse aplicado ao lead capturado nesta página.', max_length=12, verbose_name='cai no funil como')),
                ('selo_texto', models.CharField(blank=True, default='Inauguração · 31 de Outubro', max_length=80, verbose_name='selo (topo)')),
                ('hero_titulo', models.CharField(default='O Vô Testa recebia todo mundo. Agora o neto abre as portas para você.', max_length=160, verbose_name='título principal')),
                ('hero_subtitulo', models.TextField(blank=True, default='Uma pousada fora do tempo, à beira do Lago de Itá, erguida para honrar o inventor que moveu as águas — e recebia como ninguém. Seja um dos fundadores.', verbose_name='subtítulo')),
                ('historia_titulo', models.CharField(blank=True, default='O Inventor que Moveu as Águas', max_length=120, verbose_name='título da história')),
                ('historia_texto', models.TextField(blank=True, help_text='Parágrafos separados por linha em branco.', verbose_name='texto da história')),
                ('oferta_titulo', models.CharField(blank=True, default='Tarifa de Fundador', max_length=80, verbose_name='título da oferta')),
                ('oferta_texto', models.TextField(blank=True, default='Ser fundador é dormir aqui antes de todo mundo — e pagar menos por isso. A tarifa sobe a cada faixa esgotada.', verbose_name='texto da oferta')),
                ('cta_texto', models.CharField(default='Quero minha tarifa de fundador', max_length=60, verbose_name='texto do botão')),
                ('vagas_restantes', models.PositiveSmallIntegerField(blank=True, help_text="Mostra 'restam X vagas' na página. Deixe em branco para ocultar.", null=True, verbose_name='vagas restantes (opcional)')),
                ('data_evento', models.DateTimeField(blank=True, help_text='Se preenchida, mostra o contador regressivo até esta data.', null=True, verbose_name='data do evento (contador)')),
                ('meta_leads', models.PositiveIntegerField(default=0, verbose_name='meta de leads')),
                ('visitas', models.PositiveIntegerField(default=0, verbose_name='visitas')),
                ('publicada_em', models.DateTimeField(blank=True, null=True, verbose_name='publicada em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paginas_captacao', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'página de captação',
                'verbose_name_plural': 'páginas de captação',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='pagina_captacao',
            field=models.ForeignKey(blank=True, help_text='Campanha/Landing Page que gerou este lead (se veio de uma).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='comercial.paginacaptacao', verbose_name='página de captação'),
        ),
    ]
