# Generated by Django 6.0.7 on 2026-08-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_paginacaptacao_oportunidade_pagina_captacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginacaptacao',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='endereço (texto)'),
        ),
        migrations.AddField(
            model_name='paginacaptacao',
            name='faq_texto',
            field=models.TextField(blank=True, help_text="Uma pergunta por bloco. Formato: linha 'P: pergunta' e linha 'R: resposta'. Blocos separados por linha em branco.", verbose_name='perguntas frequentes'),
        ),
        migrations.AddField(
            model_name='paginacaptacao',
            name='google_tag_id',
            field=models.CharField(blank=True, help_text='ID do Google (ex.: G-XXXX ou AW-XXXX) para medir a conversão.', max_length=32, verbose_name='Google (ID da tag)'),
        ),
        migrations.AddField(
            model_name='paginacaptacao',
            name='mapa_embed',
            field=models.URLField(blank=True, help_text="URL de 'incorporar' do Google Maps (o src do iframe).", verbose_name='mapa (URL de incorporação)'),
        ),
        migrations.AddField(
            model_name='paginacaptacao',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text="ID do Pixel do Meta (Instagram/Facebook) para rastrear e refazer anúncios (retargeting). Dispara o evento 'Lead' ao cadastrar.", max_length=32, verbose_name='Meta Pixel (ID)'),
        ),
        migrations.AddField(
            model_name='paginacaptacao',
            name='whatsapp_destino',
            field=models.CharField(blank=True, help_text='Só números com país+DDD (ex.: 5549999990000). Após o cadastro, o lead é levado ao WhatsApp com uma mensagem pronta.', max_length=20, verbose_name='WhatsApp para conversão'),
        ),
    ]
