# Generated by Django 6.0.7 on 2026-08-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_paginacaptacao_endereco_paginacaptacao_faq_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginacaptacao',
            name='tagline',
            field=models.CharField(blank=True, default='vô testa, a invenção que virou história.', max_length=120, verbose_name='mote (aparece em minúsculas)'),
        ),
        migrations.AlterField(
            model_name='paginacaptacao',
            name='hero_subtitulo',
            field=models.TextField(blank=True, default='Uma pousada fora do tempo, em Itá, Santa Catarina, erguida para honrar o inventor que transformou engenhosidade em acolhimento. Seja um dos fundadores.', verbose_name='subtítulo'),
        ),
    ]
