# Generated by Django 6.0.7 on 2026-08-31 23:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_paginacaptacao_tagline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='origem_rastreio',
            field=models.JSONField(blank=True, default=dict, help_text='UTM + identificadores de clique (fbclid/gclid) para atribuição.', verbose_name='rastreio de origem'),
        ),
        migrations.AlterField(
            model_name='paginacaptacao',
            name='tagline',
            field=models.CharField(blank=True, default='a invenção que virou história.', max_length=120, verbose_name='mote (aparece em minúsculas)'),
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('codigo', models.SlugField(help_text='Use este valor no utm_campaign do anúncio para atribuir os leads.', max_length=80, unique=True, verbose_name='código (casa com utm_campaign)')),
                ('provedor', models.CharField(choices=[('meta', 'Meta (Instagram/Facebook)'), ('google', 'Google'), ('outro', 'Outra')], default='meta', max_length=10, verbose_name='provedor')),
                ('verba', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='verba planejada (R$)')),
                ('id_externo', models.CharField(blank=True, help_text='ID da campanha no Meta/Google (para a Fase C — sincronizar gasto).', max_length=64, verbose_name='ID na plataforma')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('pagina_captacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas', to='comercial.paginacaptacao', verbose_name='página de captação (destino)')),
            ],
            options={
                'verbose_name': 'campanha de anúncio',
                'verbose_name_plural': 'campanhas de anúncio',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='campanha',
            field=models.ForeignKey(blank=True, help_text='Campanha paga que trouxe o lead (casada pelo utm_campaign).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='comercial.campanha', verbose_name='campanha de anúncio'),
        ),
        migrations.CreateModel(
            name='GastoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('sincronizado', 'Sincronizado (API)')], default='manual', max_length=12, verbose_name='origem do dado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='lançado em')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='comercial.campanha', verbose_name='campanha')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_midia', to=settings.AUTH_USER_MODEL, verbose_name='lançado por')),
            ],
            options={
                'verbose_name': 'gasto de anúncio',
                'verbose_name_plural': 'gastos de anúncio',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
