# Generated by Django 6.0.7 on 2026-08-31 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_oportunidade_origem_rastreio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaoEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('lead', 'Lead'), ('compra', 'Compra / Reserva')], max_length=8, verbose_name='evento')),
                ('provedor', models.CharField(max_length=12, verbose_name='provedor')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('erro', 'Erro')], max_length=8, verbose_name='status')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor (R$)')),
                ('id_externo', models.CharField(blank=True, max_length=120, verbose_name='ID na plataforma')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversoes_enviadas', to='comercial.oportunidade', verbose_name='oportunidade')),
            ],
            options={
                'verbose_name': 'conversão enviada',
                'verbose_name_plural': 'conversões enviadas',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['oportunidade', 'evento', 'status'], name='comercial_c_oportun_b7f448_idx')],
            },
        ),
    ]
