# Generated by Django 6.0.7 on 2026-09-01 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_conversaoenviada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('ultima_msg_cliente_em', models.DateTimeField(blank=True, help_text='Abre a janela de 24h para mensagens livres.', null=True, verbose_name='última mensagem do cliente')),
                ('nao_lidas', models.PositiveSmallIntegerField(default=0, verbose_name='não lidas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('oportunidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversa_whatsapp', to='comercial.oportunidade', verbose_name='oportunidade')),
            ],
            options={
                'verbose_name': 'conversa de WhatsApp',
                'verbose_name_plural': 'conversas de WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='MensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direcao', models.CharField(choices=[('entrada', 'Recebida'), ('saida', 'Enviada')], max_length=8, verbose_name='direção')),
                ('texto', models.TextField(verbose_name='texto')),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('enviada', 'Enviada'), ('erro', 'Erro')], max_length=10, verbose_name='status')),
                ('id_externo', models.CharField(blank=True, max_length=120, verbose_name='ID externo')),
                ('horario', models.DateTimeField(verbose_name='horário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrada em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_whatsapp', to=settings.AUTH_USER_MODEL, verbose_name='autor (envio)')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='comercial.conversawhatsapp', verbose_name='conversa')),
            ],
            options={
                'verbose_name': 'mensagem de WhatsApp',
                'verbose_name_plural': 'mensagens de WhatsApp',
                'ordering': ['horario', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespostaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='título (rótulo do chip)')),
                ('texto', models.TextField(verbose_name='texto')),
                ('atalho', models.CharField(blank=True, max_length=20, verbose_name='atalho')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_rapidas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'resposta rápida',
                'verbose_name_plural': 'respostas rápidas',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
