# Generated by Django 6.0.7 on 2026-09-01 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_conversawhatsapp_mensagemwhatsapp_respostarapida'),
        ('nucleo', '0031_conceder_remuneracao_gerentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('assunto', models.CharField(max_length=200, verbose_name='assunto')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('bounce', 'Devolvido (bounce)'), ('reclamado', 'Reclamação'), ('aberto', 'Aberto'), ('erro', 'Erro')], default='pendente', max_length=10, verbose_name='status')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='message-id')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('evento_em', models.DateTimeField(blank=True, null=True, verbose_name='último evento em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_enviados', to=settings.AUTH_USER_MODEL, verbose_name='autor (envio)')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='comercial.oportunidade', verbose_name='oportunidade')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_comerciais', to='nucleo.pessoa', verbose_name='destinatário (pessoa)')),
            ],
            options={
                'verbose_name': 'envio de e-mail',
                'verbose_name_plural': 'envios de e-mail',
                'ordering': ['-criado_em'],
            },
        ),
    ]
