# Generated by Django 6.0.7 on 2026-09-02 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_envioemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('assunto', models.CharField(max_length=200, verbose_name='assunto')),
                ('corpo', models.TextField(verbose_name='corpo (abertura, com variáveis)')),
                ('blocos', models.JSONField(blank=True, default=dict, verbose_name='blocos opcionais')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates_email', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'template de e-mail',
                'verbose_name_plural': 'templates de e-mail',
                'ordering': ['nome'],
            },
        ),
    ]
