# Generated by Django 6.0.7 on 2026-09-02 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_templateemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('assunto', models.CharField(max_length=200, verbose_name='assunto')),
                ('corpo', models.TextField(verbose_name='corpo (com variáveis)')),
                ('segmento', models.JSONField(blank=True, default=dict, verbose_name='segmento (filtros)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('enviando', 'Enviando'), ('enviada', 'Enviada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=10, verbose_name='status')),
                ('agendar_para', models.DateTimeField(blank=True, null=True, verbose_name='agendar para')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='público-alvo')),
                ('enviados', models.PositiveIntegerField(default=0, verbose_name='enviados')),
                ('erros', models.PositiveIntegerField(default=0, verbose_name='erros')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('enviada_em', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_email', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas', to='comercial.templateemail', verbose_name='template de origem')),
            ],
            options={
                'verbose_name': 'campanha de e-mail',
                'verbose_name_plural': 'campanhas de e-mail',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='envioemail',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='comercial.campanhaemail', verbose_name='campanha'),
        ),
    ]
