# Generated by Django 6.0.7 on 2026-09-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0014_campanhaemail_envioemail_campanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiselead',
            name='canal_sugerido',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('ligacao', 'Ligação'), ('email', 'E-mail')], max_length=10, verbose_name='Jev — canal sugerido'),
        ),
        migrations.AddField(
            model_name='analiselead',
            name='confianca_jev',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Jev — confiança (0–1)'),
        ),
        migrations.AddField(
            model_name='analiselead',
            name='jev_avaliado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Jev — avaliado em'),
        ),
        migrations.AddField(
            model_name='analiselead',
            name='jev_modelo',
            field=models.CharField(blank=True, max_length=40, verbose_name='Jev — modelo/versão'),
        ),
        migrations.AddField(
            model_name='analiselead',
            name='qualificado_jev',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Jev — qualificado (0–1)'),
        ),
        migrations.AddField(
            model_name='analiselead',
            name='score_jev',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jev — prob. de conversão (0–100)'),
        ),
    ]
